server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8082
 # servlet:
    #context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: headwaysocial
    password: headwaysocial
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  mail:
    host: localhost
    port: 1052
    username: abc@gmail.com
    password: papadapa
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
contact:
  notify:
    to: info@headwaysocial.com

logging:
  level:
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    headway.backend: DEBUG

jwt:
  jwtSecret: headwaySecretKey82000306batatawadatamatar123123123sdfsdfsdfsd
  jwtExpirationInMilliSeconds: 3600000





